"""Add rt_ticket_number to Ticket model

Revision ID: 360c7cfe4ae4
Revises: b0848ed8d6a2
Create Date: 2025-10-24 11:05:13.323694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360c7cfe4ae4'
down_revision = 'b0848ed8d6a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rt_ticket_number', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_tickets_rt_ticket_number'), ['rt_ticket_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_rt_ticket_number'))
        batch_op.drop_column('rt_ticket_number')

    # ### end Alembic commands ###
