"""Add plan_rate to Client model

Revision ID: 4db0fbfb0237
Revises: 3dada8c29fac
Create Date: 2025-10-30 09:12:47.314751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4db0fbfb0237'
down_revision = '3dada8c29fac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_rate', sa.Float(), nullable=False, server_default='0.0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('plan_rate')

    # ### end Alembic commands ###
