"""Add email_sent column to tickets

Revision ID: 6770b39271d9
Revises: 4db0fbfb0237
Create Date: 2025-11-24 13:35:40.796402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6770b39271d9'
down_revision = '4db0fbfb0237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        # ADDED server_default=sa.text('false') to fix the SQLite error
        batch_op.add_column(
            sa.Column(
                "email_sent",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("false"),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('email_sent')

    # ### end Alembic commands ###
