"""Manually add NEW to TicketStatus enum for PostgreSQL

Revision ID: 8a1ca0f52753 # <-- This file's ID
Revises: 360c7cfe4ae4    # <-- The Previous file's ID
Create Date: <TIMESTAMP> # <-- Alembic handles this

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8a1ca0f52753"  # <-- This file's ID
down_revision = "360c7cfe4ae4"  # <-- The Previous file's ID
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # --- START OF FIX ---
    # Get the Alembic context
    bind = op.get_bind()
    # Check if the dialect (database type) is 'postgresql'
    if bind.dialect.name == "postgresql":
        # Only run this command for PostgreSQL
        op.execute("ALTER TYPE ticketstatus ADD VALUE IF NOT EXISTS 'NEW'")
    # --- END OF FIX ---

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Downgrading enum value removal is complex, skip for now
    pass
    # ### end Alembic commands ###
