"""Manually add NEW to TicketStatus enum for PostgreSQL

Revision ID: <SOME_ID_HERE>
Revises: <PREVIOUS_ID_HERE>
Create Date: <TIMESTAMP>

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "<SOME_ID_HERE>"
down_revision = "<PREVIOUS_ID_HERE>"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # ADD THIS LINE MANUALLY:
    op.execute("ALTER TYPE ticketstatus ADD VALUE IF NOT EXISTS 'NEW'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Downgrading enum value removal is complex, skip for now
    pass
    # ### end Alembic commands ###
