"""Add email_sent column to tickets

Revision ID: e1a2b3c4d5e6
Revises: 3dada8c29fac
Create Date: 2025-10-30 12:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e1a2b3c4d5e6"
down_revision = "3dada8c29fac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        # Add the email_sent column with a default value of False
        batch_op.add_column(
            sa.Column(
                "email_sent", sa.Boolean(), nullable=False, server_default="false"
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.drop_column("email_sent")

    # ### end Alembic commands ###
