"""Add last_assigned_at to users

Revision ID: ec4017fdd9a4
Revises: 97f2f606acab
Create Date: 2025-11-25 16:14:56.046479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec4017fdd9a4'
down_revision = '97f2f606acab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_assigned_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_assigned_at')

    # ### end Alembic commands ###
